"""
Address type definition file generated by TypeBuf
Note: Any changes made to this file will be overwritten
      during next compilation
"""

from typing import *


class Address:
    street_address_1: str
    street_address_2: Optional[str]
    postal_code: int
    state: str
    user: User
