/**
 * Address type definition file generated by TypeBuf
 * Note: Any changes made to this file will be overwritten
 *       during next compilation
 */

interface Address {
  street_address_1: string;
  street_address_2?: string;
  postal_code: number;
  state: string;
  user: User;
}