/**
 * Address type definition file generated by TypeBuf
 * Note: Any changes made to this file will be overwritten
 *       during next compilation
 */

import { User } from "./User";

interface Address {
  street_address_1: string;
  street_address_2?: string;
  postal_code: number | string;
  state: string;
  user: User;
}